


GET http://localhost:4004/odata/v4/noauth/Demand HTTP/1.1
###

POST http://localhost:4004/odata/v4/noauth/Demand HTTP/1.1
Content-Type: application/json

{
  "demandID": "112203",
      "project": "LG",
      "projectType": "Fixed Price",
      "deliveryType": "Managed",
      "requestorEnterpriseID": "def.03",
      "requestDate": "2024-01-12",
      "dealType": "Managed",
      "dealStatus": "Open",
      "remarks": "None"
      }

###
GET http://localhost:4004/odata/v4/noauth/DemandItems HTTP/1.1
###
POST http://localhost:4004/odata/v4/noauth/DemandItems HTTP/1.1
Content-Type: application/json

{
  "demandID": "112201",
      "project": "Dell",
      "demandItem": 1,
      "startDate": "2024-04-01",
      "endDate": "2025-10-11",
      "requiredLevel": "SE",
      "resourceSkill": "CAPM",
      "resourceLevel": "ASE",
      "resourceEnterpriseID": "abc.03",
      "resourceStatus": "Open"
  }

###
 GET http://localhost:4004/odata/v4/noauth/Resource HTTP/1.1
 

  

###
POST http://localhost:4004/odata/v4/noauth/Resource HTTP/1.1
Content-Type: application/json

{
      "enterpriseID": "abc.05",
      "employeeID": 1115,
      "employeeName": "Emp name 05",
      "location": "Chennai",
      "designation": "SE",
      "level": 10,
      "leadResourceID": "xyz.05",
      "team": "CAPM",
      "status": "Active"
}

###
 GET http://localhost:4004/odata/v4/noauth/Projects HTTP/1.1
 

####
POST http://localhost:4004/odata/v4/noauth/Projects HTTP/1.1
Content-Type: application/json

{
  "project": "Ikea",
  "projectType": "Fixed",
  "deliveryType": "unmanaged",
  "leadResource": ""
}

###
GET http://localhost:4004/odata/v4/noauth/Assignment HTTP/1.1


####
POST http://localhost:4004/odata/v4/noauth/Assignment HTTP/1.1
Content-Type: application/json

{
  "enterpriseID": "abc.01",
      "project": "Cipla",
      "allocation": "100",
      "startDate": "2024-02-22",
      "endDate": "2024-04-11",
      "assignmentStatus": "Active",
      "roleDescription": "none"
}